SELECT	A.SECTN_DEPT_ID 
,		COALESCE(A.DEPT_N, A.SECTN_N) AS DEPARTAMENTO
,		D.DIVISION_N AS ORGANIZACAO
FROM	SECTN_DEPT AS A WITH (NOLOCK, FORCESCAN, INDEX(0))
		--
		LEFT OUTER HASH JOIN SECTN AS B WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	A.SECTN_ID 		= B.SECTN_ID		
		AND	B.SECTN_ID 		<> 0
		--
		LEFT OUTER HASH JOIN BRANCH AS C WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON 	B.BRANCH_ID 	= C.BRANCH_ID 
		AND	C.BRANCH_ID		<> 0
		--
		LEFT OUTER HASH JOIN DIVISION AS D WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	C.DIVISION_ID	= D.DIVISION_ID
		AND	D.DIVISION_ID 	<> 0
		--
WHERE	A.SECTN_ID <> 0
ORDER	BY A.SECTN_DEPT_ID 