SELECT	A.USR_ID
,		A.USR_SC
,		A.USR_N
,		A.USR_RMK
,		B.USR_ROLE_ID
,		B.USR_ROLE_SC
,		B.USR_ROLE_N
,		C.SECTN_DEPT_ID
,		C.SECTN_DEPT_SC
,		D.DEPT_ID
,		D.DEPT_SC
,		D.DEPT_N
,		E.SECTN_ID
,		E.SECTN_SC
,		E.SECTN_N
,		F.BRANCH_ID
,		F.BRANCH_SC
,		F.BRANCH_N
,		G.DIVISION_ID					AS ORGANIZACAO_ID
,		G.DIVISION_SC					AS ORGANIZACAO_SC
,		G.DIVISION_N					AS ORGANIZACAO_N
,		H.COMPANY_ID					AS COMPANHIA_ID
,		H.COMPANY_SC					AS COMPANHIA_SC
,		H.COMPANY_N						AS COMPANHIA_N
,		J.BLDNG_ID						AS SITE_ID
,		J.BLDNG_SC						AS SITE_SC
,		J.BLDNG_N						AS SITE_N
,		J.BLDNG_RMK						AS SITE_RMK
,		I.BLDNG_ROOM_ID					AS SALA_SITE_ID
,		I.BLDNG_ROOM_SC					AS SALA_SITE_SC
,		I.ROOM_ID						AS SALA_ID
,		I.ROOM_SC						AS SALA_SC
,		I.ROOM_N						AS SALA_N
,		K.SITE_ID						AS CIDADE_ID
,		K.SITE_SC						AS CIDADE_SC
,		K.SITE_N						AS CIDADE_N
,		L.SITE_AREA_ID					AS ESTADO_ID
,		L.SITE_AREA_SC					AS ESTADO_SC
,		L.SITE_AREA_N					AS ESTADO_N
,		M.TERRITORY_ID					AS PAIS_ID
,		M.TERRITORY_SC					AS PAIS_SC
,		M.TERRITORY_N					AS PAIS_N
FROM	USR 							AS A
		--
		LEFT OUTER JOIN USR_ROLE 		AS B
		ON 	A.USR_ROLE_ID		= B.USR_ROLE_ID
		--
		LEFT OUTER JOIN SECTN_DEPT 		AS C
		ON	A.SECTN_DEPT_ID 	= C.SECTN_DEPT_ID
		--
		LEFT OUTER JOIN DEPT			AS D
		ON	C.DEPT_ID			= D.DEPT_ID		
		--
		LEFT OUTER JOIN SECTN			AS E
		ON	C.SECTN_ID			= E.SECTN_ID
		--
		LEFT OUTER JOIN BRANCH			AS F
		ON	E.BRANCH_ID			= F.BRANCH_ID
		--
		LEFT OUTER JOIN DIVISION		AS G
		ON	F.DIVISION_ID		= G.DIVISION_ID
		--
		LEFT OUTER JOIN COMPANY			AS H
		ON	G.COMPANY_ID		= H.COMPANY_ID
		--
		LEFT OUTER JOIN BLDNG_ROOM		AS I
		ON	A.BLDNG_ROOM_ID		= I.BLDNG_ROOM_ID
		--
		LEFT OUTER JOIN BLDNG			AS J
		ON	I.BLDNG_ID			= J.BLDNG_ID
		--
		LEFT OUTER JOIN SITE			AS K
		ON	J.SITE_ID			= K.SITE_ID
		--
		LEFT OUTER JOIN SITE_AREA		AS L
		ON	K.SITE_AREA_ID		= L.SITE_AREA_ID
		--
		LEFT OUTER JOIN TERRITORY		AS M
		ON	L.TERRITORY_ID		= M.TERRITORY_ID
		--
WHERE	1=1
--AND		A.USR_SC = 'U4UL'
ORDER	BY A.USR_ID