SELECT	A.SERV_DEPT_N 									AS MESA
--,		B.SUPPLIER_N 									AS FORNECEDOR
--,		C.SLA_N 										AS SLA	
,		CAST(CAST(C.MON_START AS TIME) AS VARCHAR(8))	AS MON_BEGIN
,		CAST(CAST(C.MON_END   AS TIME) AS VARCHAR(8))	AS MON_END
,		CAST(CAST(C.TUE_START AS TIME) AS VARCHAR(8))	AS TUE_BEGIN
,		CAST(CAST(C.TUE_END   AS TIME) AS VARCHAR(8))	AS TUE_END
,		CAST(CAST(C.WED_START AS TIME) AS VARCHAR(8))	AS WED_BEGIN
,		CAST(CAST(C.WED_END   AS TIME) AS VARCHAR(8))	AS WED_END
,		CAST(CAST(C.THR_START AS TIME) AS VARCHAR(8))	AS THR_BEGIN
,		CAST(CAST(C.THR_END   AS TIME) AS VARCHAR(8))	AS THR_END
,		CAST(CAST(C.FRI_START AS TIME) AS VARCHAR(8))	AS FRI_BEGIN
,		CAST(CAST(C.FRI_END   AS TIME) AS VARCHAR(8))	AS FRI_END
,		CAST(CAST(C.SAT_START AS TIME) AS VARCHAR(8))	AS SAT_BEGIN
,		CAST(CAST(C.SAT_END   AS TIME) AS VARCHAR(8))	AS SAT_END
,		CAST(CAST(C.SUN_START AS TIME) AS VARCHAR(8))	AS SUN_BEGIN
,		CAST(CAST(C.SUN_END   AS TIME) AS VARCHAR(8))	AS SUN_END
--,		D.HPLAN_HEAD_N		 							AS PLAN_FERIADOS
,		CAST(CAST(D.HPLAN1  AS DATE) AS VARCHAR(10))	AS FERIADO_01
,		CAST(CAST(D.HPLAN2  AS DATE) AS VARCHAR(10))	AS FERIADO_02
,		CAST(CAST(D.HPLAN3  AS DATE) AS VARCHAR(10))	AS FERIADO_03
,		CAST(CAST(D.HPLAN4  AS DATE) AS VARCHAR(10))	AS FERIADO_04
,		CAST(CAST(D.HPLAN5  AS DATE) AS VARCHAR(10))	AS FERIADO_05
,		CAST(CAST(D.HPLAN6  AS DATE) AS VARCHAR(10))	AS FERIADO_06
,		CAST(CAST(D.HPLAN7  AS DATE) AS VARCHAR(10))	AS FERIADO_07
,		CAST(CAST(D.HPLAN8  AS DATE) AS VARCHAR(10))	AS FERIADO_08
,		CAST(CAST(D.HPLAN9  AS DATE) AS VARCHAR(10))	AS FERIADO_09
,		CAST(CAST(D.HPLAN10 AS DATE) AS VARCHAR(10))	AS FERIADO_10
,		CAST(CAST(D.HPLAN11 AS DATE) AS VARCHAR(10))	AS FERIADO_11
,		CAST(CAST(D.HPLAN12 AS DATE) AS VARCHAR(10))	AS FERIADO_12
,		CAST(CAST(D.HPLAN13 AS DATE) AS VARCHAR(10))	AS FERIADO_13
,		CAST(CAST(D.HPLAN14 AS DATE) AS VARCHAR(10))	AS FERIADO_14
,		CAST(CAST(D.HPLAN15 AS DATE) AS VARCHAR(10))	AS FERIADO_15
,		CAST(CAST(D.HPLAN16 AS DATE) AS VARCHAR(10))	AS FERIADO_16
,		CAST(CAST(D.HPLAN17 AS DATE) AS VARCHAR(10))	AS FERIADO_17
,		CAST(CAST(D.HPLAN18 AS DATE) AS VARCHAR(10))	AS FERIADO_18
,		CAST(CAST(D.HPLAN19 AS DATE) AS VARCHAR(10))	AS FERIADO_19
,		CAST(CAST(D.HPLAN20 AS DATE) AS VARCHAR(10))	AS FERIADO_20
FROM	SERV_DEPT AS A
		--
		LEFT OUTER JOIN SUPPLIER AS B
		ON 	A.EQUIV_SUPP_ID = B.SUPPLIER_ID
		AND	B.SUPPLIER_ID <> 0
		--
		LEFT OUTER JOIN SLA AS C
		ON	B.DFLT_SLA_ID 	=  C.SLA_ID
		AND	C.SLA_ID 		<> 0
		--
		LEFT OUTER JOIN HPLAN_HEAD AS D
		ON	C.HPLAN_HEAD_ID = D.HPLAN_HEAD_ID
		AND	C.HPLAN_HEAD_ID	<> 0
		-- 
WHERE	A.SERV_DEPT_ID 	<> 0
AND		B.supplier_id 	IS NOT NULL
ORDER	BY 1