SELECT	A.BLDNG_ROOM_ID  
,		A.BLDNG_N 
,		B.BLDNG_RMK 
,		A.ROOM_N
,		C.SITE_N
,		D.SITE_AREA_SC
FROM	BLDNG_ROOM AS A WITH (NOLOCK, FORCESCAN, INDEX(0))
		--
		LEFT OUTER HASH JOIN BLDNG	 AS B WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	A.BLDNG_ID = B.BLDNG_ID
		AND	B.BLDNG_ID <> 0
		--
		LEFT OUTER JOIN SITE AS C WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	B.SITE_ID = C.SITE_ID
		AND C.SITE_ID <> 0
		--
		LEFT OUTER HASH JOIN SITE_AREA AS D WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	C.SITE_AREA_ID = D.SITE_AREA_ID
		AND	D.SITE_AREA_ID <> 0
		--
WHERE	A.BLDNG_ROOM_ID <> 0
ORDER	BY A.BLDNG_ROOM_ID