SELECT	A.SERV_DEPT_ID									AS MESA_ID
,		A.SERV_DEPT_SC 									AS MESA_SC
,		A.SERV_DEPT_N 									AS MESA_N
,		B.SUPPLIER_ID 									AS FORNECEDOR_ID
,		B.SUPPLIER_SC 									AS FORNECEDOR_SC
,		B.SUPPLIER_N 									AS FORNECEDOR_N
,		C.SLA_ID 										AS SLA_ID	
,		C.SLA_SC 										AS SLA_SC
,		C.SLA_N 										AS SLA_N
,		CAST(CAST(C.MON_START AS TIME) AS VARCHAR(8))	AS MON_BEGIN
,		CAST(CAST(C.MON_END   AS TIME) AS VARCHAR(8))	AS MON_END
,		CAST(CAST(C.TUE_START AS TIME) AS VARCHAR(8))	AS TUE_BEGIN
,		CAST(CAST(C.TUE_END   AS TIME) AS VARCHAR(8))	AS TUE_END
,		CAST(CAST(C.WED_START AS TIME) AS VARCHAR(8))	AS WED_BEGIN
,		CAST(CAST(C.WED_END   AS TIME) AS VARCHAR(8))	AS WED_END
,		CAST(CAST(C.THR_START AS TIME) AS VARCHAR(8))	AS THR_BEGIN
,		CAST(CAST(C.THR_END   AS TIME) AS VARCHAR(8))	AS THR_END
,		CAST(CAST(C.FRI_START AS TIME) AS VARCHAR(8))	AS FRI_BEGIN
,		CAST(CAST(C.FRI_END   AS TIME) AS VARCHAR(8))	AS FRI_END
,		CAST(CAST(C.SAT_START AS TIME) AS VARCHAR(8))	AS SAT_BEGIN
,		CAST(CAST(C.SAT_END   AS TIME) AS VARCHAR(8))	AS SAT_END
,		CAST(CAST(C.SUN_START AS TIME) AS VARCHAR(8))	AS SUN_BEGIN
,		CAST(CAST(C.SUN_END   AS TIME) AS VARCHAR(8))	AS SUN_END
,		CONVERT(VARCHAR(10), D.HPLAN1 , 120)			AS FERIADO_01
,		CONVERT(VARCHAR(10), D.HPLAN2 , 120)			AS FERIADO_02
,		CONVERT(VARCHAR(10), D.HPLAN3 , 120)			AS FERIADO_03
,		CONVERT(VARCHAR(10), D.HPLAN4 , 120)			AS FERIADO_04
,		CONVERT(VARCHAR(10), D.HPLAN5 , 120)			AS FERIADO_05
,		CONVERT(VARCHAR(10), D.HPLAN6 , 120)			AS FERIADO_06
,		CONVERT(VARCHAR(10), D.HPLAN7 , 120)			AS FERIADO_07
,		CONVERT(VARCHAR(10), D.HPLAN8 , 120)			AS FERIADO_08
,		CONVERT(VARCHAR(10), D.HPLAN9 , 120)			AS FERIADO_09
,		CONVERT(VARCHAR(10), D.HPLAN10, 120)			AS FERIADO_10
,		CONVERT(VARCHAR(10), D.HPLAN11, 120)			AS FERIADO_11
,		CONVERT(VARCHAR(10), D.HPLAN12, 120)			AS FERIADO_12
,		CONVERT(VARCHAR(10), D.HPLAN13, 120)			AS FERIADO_13
,		CONVERT(VARCHAR(10), D.HPLAN14, 120)			AS FERIADO_14
,		CONVERT(VARCHAR(10), D.HPLAN15, 120)			AS FERIADO_15
,		CONVERT(VARCHAR(10), D.HPLAN16, 120)			AS FERIADO_16
,		CONVERT(VARCHAR(10), D.HPLAN17, 120)			AS FERIADO_17
,		CONVERT(VARCHAR(10), D.HPLAN18, 120)			AS FERIADO_18
,		CONVERT(VARCHAR(10), D.HPLAN19, 120)			AS FERIADO_19
,		CONVERT(VARCHAR(10), D.HPLAN20, 120)			AS FERIADO_20
FROM	SERV_DEPT AS A
		--
		LEFT OUTER JOIN SUPPLIER AS B
		ON 	A.EQUIV_SUPP_ID = B.SUPPLIER_ID
		AND	B.SUPPLIER_ID <> 0
		--
		LEFT OUTER JOIN SLA AS C
		ON	B.DFLT_SLA_ID 	=  C.SLA_ID
		AND	C.SLA_ID 		<> 0
		--
		LEFT OUTER JOIN HPLAN_HEAD AS D
		ON	C.HPLAN_HEAD_ID = D.HPLAN_HEAD_ID
		AND	C.HPLAN_HEAD_ID	<> 0
		-- 
WHERE	A.SERV_DEPT_ID 		<> 0
AND		B.supplier_id 		IS NOT NULL
ORDER	BY A.SERV_DEPT_ID