SELECT	A.ITEM_ID
,		A.ITEM_N
,		B.PRODUCT_ID
,		B.PRODUCT_N
,		C.PROD_CLS_ID 
,		C.PROD_CLS_N 
,		D.GENERIC_CLS_ID 
,		D.GENERIC_CLS_N 
,		E.SUPPLIER_ID 
,		E.SUPPLIER_N
FROM	ITEM AS A WITH (NOLOCK, FORCESCAN, INDEX(0))
		--
		INNER HASH JOIN PRODUCT AS B WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON 	A.PRODUCT_ID 				= B.PRODUCT_ID
		AND	B.PRODUCT_ID 				<> 0
		--
		INNER HASH JOIN PROD_CLS AS C WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	B.PROD_CLS_ID 				= C.PROD_CLS_ID
		AND	C.PROD_CLS_ID				<> 0
		--
		INNER HASH JOIN GENERIC_CLS AS D WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	C.GENERIC_CLS_ID 			= D.GENERIC_CLS_ID 
		AND	D.GENERIC_CLS_ID 			<> 0
		--
		INNER JOIN SUPPLIER AS E WITH (NOLOCK, FORCESCAN, INDEX(0))
		ON	B.SUPPLIER_ID 				= E.SUPPLIER_ID
		AND	E.SUPPLIER_ID 				<> 0
		--
WHERE	A.ITEM_ID 						<> 0
ORDER	BY A.ITEM_ID