-- SELECT CLAUSE
SELECT	'WHEN ULTIMA_ACAO_NOME = ''' 
+ 		ACT_TYPE_N + ''' THEN ''' 
+		CASE 	WHEN USER_STATUS = 'y' THEN 'USER STATUS'
		        WHEN USER_STATUS = 'n' THEN 'NONE'
		        WHEN USER_STATUS = 's' THEN 'STAGE ACTION'
		        WHEN USER_STATUS = 'e' THEN 'BOTH STAGE AND USER STATUS'
		        WHEN USER_STATUS = 'c' THEN 'INTERNAL STOP CLOCK'
		        WHEN USER_STATUS = 'l' THEN 'USER STATUS AND INT. STOP CLOCK'
		        WHEN USER_STATUS = 't' THEN 'INTERNAL START CLOCK'
		        WHEN USER_STATUS = 'u' THEN 'SUPPLIER STOP CLOCK'
		        WHEN USER_STATUS = 'p' THEN 'SUPPLIER START CLOCK'
		        WHEN USER_STATUS = 'a' THEN 'USER STATUS AND INT. START CLOCK '
				ELSE '???'
		END
+ 		''' -- ''' + USER_STATUS + '''' AS SQL_CASE
FROM	ACT_TYPE
WHERE	ACT_TYPE_ID <> 0
AND		USER_STATUS NOT IN ('n', 's')
ORDER	BY USER_STATUS
,		ACT_TYPE_N

-- WHERE CLAUSE
SELECT	'ULTIMA_ACAO_NOME IN ( NULL ' AS SQL_WHERE
UNION	ALL
SELECT	',		 ''' + ACT_TYPE_N + ''''
FROM	ACT_TYPE
WHERE	ACT_TYPE_ID <> 0
AND		USER_STATUS NOT IN ('n', 's')
UNION	ALL
SELECT 	')'