-- SELECT * FROM INDICADORES ORDER BY ORDEM
DELETE FROM INDICADORES;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO) 
SELECT	'PRP' AS INDICADOR, 1 AS ORDEM, PRP AS VALOR
,		'Violações ' 					|| VIOLACOES  || 
		' / Incidentes '				|| INCIDENTES ||
		' > Encerrados: ' 				|| ENCERRADOS || 
		' | Resolvidos: ' 				|| RESOLVIDOS || 
		' | Cancelados: ' 				|| CANCELADOS AS OBSERVACAO
FROM 	VW_KPI_PRP AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRO' AS INDICADOR, 2 AS ORDEM, PRO AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRO AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRC' AS INDICADOR, 3 AS ORDEM, PRC AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRC AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRS' AS INDICADOR, 4 AS ORDEM, PRS AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRS AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRS - Simples' AS INDICADOR, 5 AS ORDEM, PRS_SIMPLES AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRS_SIMPLES AS A;


INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRS - Médio' AS INDICADOR, 6 AS ORDEM, PRS_MEDIO AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRS_MEDIO AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'PRS - Complexo' AS INDICADOR, 7 AS ORDEM, PRS_COMPLEXO AS VALOR
,		'Violações ' 					|| VIOLACOES  	|| 
		' / Incidentes '				|| INCIDENTES 	||
		' > Encerrados: ' 				|| ENCERRADOS 	|| 
		' | Resolvidos: ' 				|| RESOLVIDOS 	|| 
		' | Cancelados: ' 				|| CANCELADOS 	||
		' | Encaminhados: ' 			|| ENCAMINHADOS	||
		' | Priorizados: ' 				|| PRIORIZADOS 	AS OBSERVACAO
FROM 	VW_KPI_PRS_COMPLEXO AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'IDS' AS INDICADOR, 8 AS ORDEM, IDS AS VALOR
,		'Estourados ' 		|| INCIDENTES		|| 
		' - 0h - 180h: '	|| IDS_0H_180H 		||
		' | 180h - 360h: ' 	|| IDS_180H_360H	|| 
		' | 360h - 540h: ' 	|| IDS_360H_540H	|| 
		' | 540h - 720h: ' 	|| IDS_540H_720H	||
		' | 720h - 900hs: '	|| IDS_720H_900H	||
		' | > 900h : ' 		|| IDS_GT_900H	AS OBSERVACAO
FROM 	VW_KPI_IDS AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'CRI' AS INDICADOR, 9 AS ORDEM, CRI AS VALOR
,		'Tratados ' 					|| ( A.TRATADOS_ENCERRADOS + A.TRATADOS_CANCELADOS + A.TRATADOS_RESOLVIDOS + A.TRATADOS_ENCAMINHADOS) 	 
||		' / Recebidos '					|| A.RECEBIDOS_FORA_CONTRATO
||		' > Trat.s. por Encer.: ' 		|| A.TRATADOS_ENCERRADOS
||		' | Trat.s. por Canc.: ' 		|| A.TRATADOS_CANCELADOS
||		' | Trat.s por Resolução: ' 	|| A.TRATADOS_RESOLVIDOS
||		' | Trat.s por Encaminh..: ' 	|| A.TRATADOS_ENCAMINHADOS AS OBSERVACAO
FROM 	VW_KPI_CRI AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
SELECT	'SIT' AS INDICADOR, 10 AS ORDEM, SIT AS VALOR
,		'Incidentes ' 					|| INCIDENTES || 
		' / (Méd. Incs. Recebidos) '	|| MEDIA_INCS_RECEBIDOS AS OBSERVACAO
FROM 	VW_KPI_SIT AS A;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)
SELECT	'NUM_ESTORNOS' AS INDICADOR, 11 AS ORDEM, COUNT(*) AS VALOR
,		'Número de estornos cadastrados na tabela INCIDENTES_OVERRIDE'
FROM 	INCIDENTES_OVERRIDE WHERE ESTORNO = 'S';

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)
SELECT	'NUM_AJUSTES' AS INDICADOR, 12 AS ORDEM, COUNT(*) AS VALOR
,		'Número de estornos cadastrados na tabela INCIDENTES_OVERRIDE'
FROM 	INCIDENTES_OVERRIDE WHERE COALESCE(ESTORNO, 'N') <> 'S';

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)
SELECT	'DADOS_FALTANDO' AS INDICADOR, 13 AS ORDEM, COUNT(*) AS VALOR
,		'Número incidentes com dados faltando não tratados conforme view VW_DADOS_FALTANDO'
FROM 	VW_DADOS_MEDICAO_FALTANDO;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
WITH DADOS AS (
	SELECT 	COUNT(*) AS QTD
	,		SUM(CASE WHEN STATUS = 'ENCERRADO' THEN 1 ELSE 0 END) AS ENCERRADOS 
	,		SUM(CASE WHEN STATUS = 'EM ABERTO' THEN 1 ELSE 0 END) AS ABERTOS
	,		SUM(CASE WHEN STATUS = 'ENCAMINHADO' THEN 1 ELSE 0 END) AS ENCAMINHADOS
	,		SUM(CASE WHEN STATUS = 'CANCELADO' THEN 1 ELSE 0 END) AS CANCELADOS
	,		SUM(CASE WHEN STATUS = 'RESOLVIDO' THEN 1 ELSE 0 END) AS RESOLVIDOS
	,		SUM(CASE WHEN STATUS IS NULL THEN 1 ELSE 0 END) AS INDETERMINADOS
	FROM 	VW_DADOS_MEDICAO
	WHERE	PESO <> 35	
)
SELECT	'INCIDENTES' AS INDICADOR, 14 AS ORDEM, QTD AS VALOR
,		' Encerrados: ' 		|| ENCERRADOS 	|| 
		' / Abertos: '			|| ABERTOS		||
		' / Encaminhados: '		|| ENCAMINHADOS	||
		' / Cancelados: '		|| CANCELADOS	||
		' / Resolvidos: '		|| RESOLVIDOS	||
		' / Indeterminados: '	|| INDETERMINADOS AS OBSERVAO		
FROM	DADOS;

INSERT OR REPLACE INTO INDICADORES(INDICADOR, ORDEM, VALOR, OBSERVACAO)  
WITH DADOS AS (
	SELECT 	COUNT(*) AS QTD
	,		SUM(CASE WHEN STATUS = 'ENCERRADO' THEN 1 ELSE 0 END) AS ENCERRADOS 
	,		SUM(CASE WHEN STATUS = 'EM ABERTO' THEN 1 ELSE 0 END) AS ABERTOS
	,		SUM(CASE WHEN STATUS = 'CANCELADO' THEN 1 ELSE 0 END) AS CANCELADOS
	,		SUM(CASE WHEN STATUS = 'RESOLVIDO' THEN 1 ELSE 0 END) AS RESOLVIDOS
	,		SUM(CASE WHEN STATUS IS NULL THEN 1 ELSE 0 END) AS INDETERMINADOS
	FROM 	VW_DADOS_MEDICAO
	WHERE	PESO = 35	
)
SELECT	'INCIDENTES - PESO 35' AS INDICADOR, 15 AS ORDEM, QTD AS VALOR
,		' Encerrados: ' 		|| ENCERRADOS 	|| 
		' / Abertos: '			|| ABERTOS		||
		' / Cancelados: '		|| CANCELADOS	||
		' / Resolvidos: '		|| RESOLVIDOS	||
		' / Indeterminados: '	|| INDETERMINADOS AS OBSERVAO		
FROM	DADOS;