-- DROP TABLE INCIDENTES
CREATE TABLE INCIDENTES(
	ID_CHAMADO					TEXT
,	DATA_ABERTURA_CHAMADO		TEXT
,	DATA_RESOLUCAO_CHAMADO		TEXT
,	CHAMADO_PAI					TEXT
,	FCR							TEXT
,	STATUS_DE_EVENTO			TEXT
,	CATEGORIA_MAIOR				TEXT
,	CATEGORIA					TEXT
,	SERVICO_CATALOGO			TEXT
,	OFERTA_CATALOGO				TEXT
,	PRAZO_OFERTA_M				INTEGER
,	RESUMO						TEXT
,	PRAZO_PRIORIDADE_ANS_M		INTEGER
,	TEMPO_TOTAL_EVENTO_M		INTEGER
,	TEMPO_UTIL_EVENTO_M			INTEGER
,	VINCULO						TEXT
,	VINCULO_COM_INCIDENTE_GRAVE	TEXT
,	INCIDENTE_GRAVE				TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE INCIDENTE_SOLICITANTES 
CREATE TABLE INCIDENTE_SOLICITANTES (
	ID_CHAMADO					TEXT
,	ORIGEM_CHAMADO				TEXT
,	USUARIO_AFETADO				TEXT
,	NOME_DO_USUARIO_AFETADO		TEXT
,	USUARIO_INFORMANTE			TEXT
,	NOME_DO_USUARIO_INFORMANTE	TEXT
,	ORGANIZACAO_CLIENTE			TEXT
,	DEPARTAMENTO_CLIENTE		TEXT
,	ESTADO						TEXT
,	SITE						TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE INCIDENTE_ITENS_SERVICO
CREATE TABLE INCIDENTE_ITENS_SERVICO(
	ID_CHAMADO						TEXT
,	CLASSE_DE_PRODUTO_DE_SERVICO	TEXT
,	PRODUTO_DE_SERVICO				TEXT
,	ITEM_DE_SERVICO					TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE INCIDENTE_ITENS_B
CREATE TABLE INCIDENTE_ITENS_B(
	ID_CHAMADO						TEXT
,	CLASSE_GENERICA_B				TEXT
,	CLASSE_DE_PRODUTO_B				TEXT
,	PRODUTO_B						TEXT
,	FABRICANTE_B					TEXT
,	ITEM_MODELO_B					TEXT
,	ITEM_B							TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE INCIDENTE_ITENS_CAUSA
CREATE TABLE INCIDENTE_ITENS_CAUSA(
	ID_CHAMADO						TEXT
,	CATEGORIA_CAUSA					TEXT
,	CLASSE_GENERICA_CAUSA			TEXT
,	CLASSE_DE_PRODUTO_CAUSA			TEXT
,	PRODUTO_CAUSA					TEXT
,	FABRICANTE_CAUSA				TEXT
,	ITEM_MODELO_CAUSA				TEXT
,	ITEM_CAUSA						TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE INCIDENTE_ACOES
CREATE TABLE INCIDENTE_ACOES(
	ID_CHAMADO						TEXT
,	ID_ACAO							TEXT
,	RESOLUCAO						TEXT
,	ULTIMA_ACAO_NOME				TEXT
,	DATA_INICIO_ACAO				TEXT
,	DATA_FIM_ACAO					TEXT
,	ULTIMA_ACAO						TEXT
,	TEMPO_TOTAL_DA_ACAO_M			INTEGER
,	MOTIVO_PENDENCIA				TEXT
,	CAMPOS_ALTERADOS				TEXT
,	ITENS_ALTERADOS					TEXT
,	NOME_DO_CA						TEXT
,	DESCRICAO_DA_PRIORIDADE_DO_CA	TEXT
,	PRIORIDADE_DO_CA				TEXT
,	CONTRATO						TEXT
,	MESA							TEXT
,	DESIGNADO						TEXT
,	GRUPO_DEFAULT					TEXT
,	PRAZO_PRIORIDADE_ANO_M			INTEGER
,	PRAZO_PRIORIDADE_CA_M			INTEGER
,	TEMPO_UTIL_ATRIBUICAO_MESA_M	INTEGER
,	TEMPO_UTIL_ATRIBUICAO_CA_M		INTEGER
,	PRIMARY KEY(ID_CHAMADO ASC, ID_ACAO ASC)
);

-- DROP TABLE INCIDENTES_OVERRIDE
CREATE TABLE INCIDENTES_OVERRIDE(
	ID_CHAMADO						TEXT
,	CATEGORIA						TEXT
,	MESA							TEXT
,	PESO							INTEGER
,	SLA								INTEGER
,	DURACAO							INTEGER
,	ESTORNO							TEXT
,	OBSERVACAO						TEXT
,	PRIMARY KEY(ID_CHAMADO ASC)
);

-- DROP TABLE MESAS_N4_SAP
CREATE TABLE MESAS_N4_SAP(
	MESA							TEXT
,	PESO_DEFAULT					INTEGER
,	CONSIDERA_ULTIMA				TEXT
,	PRIMARY KEY(MESA ASC)
);


INSERT INTO INCIDENTES(
	ID_CHAMADO
,	DATA_ABERTURA_CHAMADO
,	DATA_RESOLUCAO_CHAMADO
,	CHAMADO_PAI
,	FCR
,	STATUS_DE_EVENTO
,	CATEGORIA_MAIOR
,	CATEGORIA
,	SERVICO_CATALOGO
,	OFERTA_CATALOGO
,	PRAZO_OFERTA_M
,	RESUMO
,	PRAZO_PRIORIDADE_ANS_M
,	TEMPO_TOTAL_EVENTO_M
,	TEMPO_UTIL_EVENTO_M
,	VINCULO
,	VINCULO_COM_INCIDENTE_GRAVE
,	INCIDENTE_GRAVE
)
SELECT	DISTINCT ID_CHAMADO
,		DATA_ABERTURA_CHAMADO
,		DATA_RESOLUCAO_CHAMADO
,		CHAMADO_PAI
,		FCR
,		STATUS_DE_EVENTO
,		CATEGORIA_MAIOR
,		CATEGORIA
,		SERVICO_CATALOGO
,		OFERTA_CATALOGO
,		PRAZO_OFERTA_M
,		RESUMO
,		PRAZO_PRIORIDADE_ANS_M
,		TEMPO_TOTAL_EVENTO_M
,		TEMPO_UTIL_EVENTO_M
,		VINCULO
,		VINCULO_COM_INCIDENTE_GRAVE
,		INCIDENTE_GRAVE
FROM	REL_MEDICAO;

INSERT INTO INCIDENTE_SOLICITANTES (
	ID_CHAMADO
,	ORIGEM_CHAMADO
,	USUARIO_AFETADO
,	NOME_DO_USUARIO_AFETADO
,	USUARIO_INFORMANTE
,	NOME_DO_USUARIO_INFORMANTE
,	ORGANIZACAO_CLIENTE
,	DEPARTAMENTO_CLIENTE
,	ESTADO
,	SITE
)
SELECT	DISTINCT ID_CHAMADO
,		ORIGEM_CHAMADO
,		USUARIO_AFETADO
,		NOME_DO_USUARIO_AFETADO
,		USUARIO_INFORMANTE
,		NOME_DO_USUARIO_INFORMANTE
,		ORGANIZACAO_CLIENTE
,		DEPARTAMENTO_CLIENTE
,		ESTADO
,		SITE
FROM	REL_MEDICAO;

INSERT INTO INCIDENTE_ITENS_SERVICO(
	ID_CHAMADO
,	CLASSE_DE_PRODUTO_DE_SERVICO
,	PRODUTO_DE_SERVICO
,	ITEM_DE_SERVICO
)
SELECT	DISTINCT ID_CHAMADO
,		CLASSE_DE_PRODUTO_DE_SERVICO
,		PRODUTO_DE_SERVICO
,		ITEM_DE_SERVICO
FROM	REL_MEDICAO;

INSERT INTO INCIDENTE_ITENS_B(
	ID_CHAMADO
,	CLASSE_GENERICA_B
,	CLASSE_DE_PRODUTO_B
,	PRODUTO_B
,	FABRICANTE_B
,	ITEM_MODELO_B
,	ITEM_B
)
SELECT	DISTINCT ID_CHAMADO
,		CLASSE_GENERICA_B
,		CLASSE_DE_PRODUTO_B
,		PRODUTO_B
,		FABRICANTE_B
,		ITEM_MODELO_B
,		ITEM_B
FROM	REL_MEDICAO;


INSERT INTO INCIDENTE_ITENS_CAUSA(
	ID_CHAMADO
,	CATEGORIA_CAUSA
,	CLASSE_GENERICA_CAUSA
,	CLASSE_DE_PRODUTO_CAUSA
,	PRODUTO_CAUSA
,	FABRICANTE_CAUSA
,	ITEM_MODELO_CAUSA
,	ITEM_CAUSA
)
SELECT	DISTINCT ID_CHAMADO
,		CATEGORIA_CAUSA
,		CLASSE_GENERICA_CAUSA
,		CLASSE_DE_PRODUTO_CAUSA
,		PRODUTO_CAUSA
,		FABRICANTE_CAUSA
,		ITEM_MODELO_CAUSA
,		ITEM_CAUSA
FROM	REL_MEDICAO;

INSERT INTO INCIDENTE_ACOES(
	ID_CHAMADO
,	ID_ACAO
,	RESOLUCAO
,	ULTIMA_ACAO_NOME
,	DATA_INICIO_ACAO
,	DATA_FIM_ACAO
,	ULTIMA_ACAO
,	TEMPO_TOTAL_DA_ACAO_M
,	MOTIVO_PENDENCIA
,	CAMPOS_ALTERADOS
,	ITENS_ALTERADOS
,	NOME_DO_CA
,	DESCRICAO_DA_PRIORIDADE_DO_CA
,	PRIORIDADE_DO_CA
,	CONTRATO
,	MESA
,	DESIGNADO
,	GRUPO_DEFAULT
,	PRAZO_PRIORIDADE_ANO_M
,	PRAZO_PRIORIDADE_CA_M
,	TEMPO_UTIL_ATRIBUICAO_MESA_M
,	TEMPO_UTIL_ATRIBUICAO_CA_M
)
SELECT	DISTINCT ID_CHAMADO
,		ID_ACAO
,		RESOLUCAO
,		ULTIMA_ACAO_NOME
,		DATA_INICIO_ACAO
,		DATA_FIM_ACAO
,		ULTIMA_ACAO
,		TEMPO_TOTAL_DA_ACAO_M
,		MOTIVO_PENDENCIA
,		CAMPOS_ALTERADOS
,		ITENS_ALTERADOS
,		NOME_DO_CA
,		DESCRICAO_DA_PRIORIDADE_DO_CA
,		PRIORIDADE_DO_CA
,		CONTRATO
,		MESA
,		DESIGNADO
,		GRUPO_DEFAULT
,		PRAZO_PRIORIDADE_ANO_M
,		PRAZO_PRIORIDADE_CA_M
,		TEMPO_UTIL_ATRIBUICAO_MESA_M
,		TEMPO_UTIL_ATRIBUICAO_CA_M
FROM	REL_MEDICAO
ORDER	BY ID_CHAMADO
,		ID_ACAO;

INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-ABAST_GE', 		 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-APOIO_OPERACAO', 	 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-CORPORATIVO',  	 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-FINANCAS', 		 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-GRC', 			 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-PORTAL', 			 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-SERVICOS', 		 1, 'S');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-ESCALADOS', 		30, 'N');
INSERT INTO MESAS_N4_SAP(MESA, PESO_DEFAULT, CONSIDERA_ULTIMA) VALUES('N4-SAP-SUSTENTACAO-PRIORIDADE', 		35, 'N');

CREATE TABLE MESAS_N4_SAP(
	MESA							TEXT
,	PESO_DEFAULT					INTEGER
,	CONSIDERA_ULTIMA				TEXT
,	PRIMARY KEY(MESA ASC)
);

-- QUERY CONFERÊNCIA
-- DROP VIEW VW_REL_MEDICAO
CREATE VIEW VW_REL_MEDICAO AS 
	SELECT	A.ID_CHAMADO
	,		A.DATA_ABERTURA_CHAMADO
	,		A.DATA_RESOLUCAO_CHAMADO
	,		A.CHAMADO_PAI
	,		B.ORIGEM_CHAMADO
	,		B.USUARIO_AFETADO
	,		B.NOME_DO_USUARIO_AFETADO
	,		B.USUARIO_INFORMANTE
	,		B.NOME_DO_USUARIO_INFORMANTE
	,		B.ORGANIZACAO_CLIENTE
	,		B.DEPARTAMENTO_CLIENTE
	,		B.ESTADO
	,		B.SITE
	,		A.FCR
	,		A.STATUS_DE_EVENTO
	,		A.CATEGORIA_MAIOR
	,		A.RESUMO
	,		A.SERVICO_CATALOGO
	,		C.CLASSE_DE_PRODUTO_DE_SERVICO
	,		C.PRODUTO_DE_SERVICO
	,		C.ITEM_DE_SERVICO
	,		A.CATEGORIA
	,		A.OFERTA_CATALOGO
	,		D.CLASSE_GENERICA_B
	,		D.CLASSE_DE_PRODUTO_B
	,		D.PRODUTO_B
	,		D.FABRICANTE_B
	,		D.ITEM_MODELO_B
	,		D.ITEM_B
	,		E.CATEGORIA_CAUSA
	,		E.CLASSE_GENERICA_CAUSA
	,		E.CLASSE_DE_PRODUTO_CAUSA
	,		E.PRODUTO_CAUSA
	,		E.FABRICANTE_CAUSA
	,		E.ITEM_MODELO_CAUSA
	,		E.ITEM_CAUSA
	,		F.RESOLUCAO
	,		F.ID_ACAO
	,		F.DATA_INICIO_ACAO
	,		F.ULTIMA_ACAO
	,		F.DATA_FIM_ACAO
	,		F.TEMPO_TOTAL_DA_ACAO_M
	,		F.ULTIMA_ACAO_NOME
	,		F.MOTIVO_PENDENCIA
	,		F.CAMPOS_ALTERADOS
	,		F.ITENS_ALTERADOS
	,		F.NOME_DO_CA
	,		F.CONTRATO
	,		F.MESA
	,		F.DESIGNADO
	,		F.GRUPO_DEFAULT
	,		F.PRIORIDADE_DO_CA
	,		F.DESCRICAO_DA_PRIORIDADE_DO_CA
	,		A.PRAZO_PRIORIDADE_ANS_M
	,		F.PRAZO_PRIORIDADE_ANO_M
	,		F.PRAZO_PRIORIDADE_CA_M
	,		A.TEMPO_TOTAL_EVENTO_M
	,		A.TEMPO_UTIL_EVENTO_M
	,		F.TEMPO_UTIL_ATRIBUICAO_MESA_M
	,		F.TEMPO_UTIL_ATRIBUICAO_CA_M
	,		A.VINCULO
	,		A.VINCULO_COM_INCIDENTE_GRAVE
	,		A.INCIDENTE_GRAVE
	,		A.PRAZO_OFERTA_M
	FROM	INCIDENTES AS A
			--
			INNER JOIN INCIDENTE_SOLICITANTES AS B
			ON A.ID_CHAMADO = B.ID_CHAMADO
			--
			INNER JOIN INCIDENTE_ITENS_SERVICO AS C
			ON A.ID_CHAMADO = C.ID_CHAMADO
			--
			INNER JOIN INCIDENTE_ITENS_B AS D
			ON A.ID_CHAMADO = D.ID_CHAMADO
			--
			INNER JOIN INCIDENTE_ITENS_CAUSA E
			ON A.ID_CHAMADO = E.ID_CHAMADO
			--
			INNER JOIN INCIDENTE_ACOES AS F
			ON A.ID_CHAMADO = F.ID_CHAMADO
			--
	ORDER	BY A.ID_CHAMADO
	,		A.CHAMADO_PAI
	,		F.DATA_INICIO_ACAO
	,		F.ID_ACAO
	,		A.STATUS_DE_EVENTO;

-- DROP VIEW VW_STATUS_CHAMADO
CREATE VIEW VW_STATUS_CHAMADO AS
	SELECT	A.ID_CHAMADO 
	,		CASE	WHEN B.DATA_RESOLUCAO_CHAMADO IS NULL 	THEN 'EM ABERTO'
					WHEN A.ULTIMA_ACAO_NOME IN ('Encerrar') THEN 'ENCERRADO'
					WHEN A.ULTIMA_ACAO_NOME IN ('Cancelado') THEN 'CANCELADO'
					ELSE NULL
			END AS FOO 		
	FROM	INCIDENTE_ACOES AS A
			--
			INNER JOIN INCIDENTES AS B
			ON	A.ID_CHAMADO = B.ID_CHAMADO
			--
	WHERE	A.ID_ACAO IN ( SELECT MAX(ID_ACAO) AS MAX_ID_ACAO FROM INCIDENTE_ACOES GROUP BY ID_CHAMADO )
	ORDER 	BY A.ID_CHAMADO;
	
-- DROP VIEW VW_ULTIMAS_MESAS	
CREATE VIEW VW_ULTIMAS_MESAS AS 
	WITH ULTIMAS_ATRIBUICOES AS (
		SELECT	MAX(ID_ACAO) as MAX_ID_ACAO
		FROM	INCIDENTE_ACOES ia 
		WHERE	ULTIMA_ACAO_NOME = 'Atribuição interna'
		AND		ID_CHAMADO IN (SELECT ID_CHAMADO FROM INCIDENTES WHERE CATEGORIA_MAIOR <> 'Demandas Internas'
		AND		MESA NOT IN (
				    'A DEFINIR',
				    'Atendimento de RH',
				    'Mesa Padrão',
				    'SVD Manager Template',
				    'Usuários Finais',
				    'N4-SAP-SUSTENTACAO-PRIORIDADE',
				    'N4-SAP-SUSTENTACAO-ESCALADOS'
			    )
		GROUP	BY ID_CHAMADO
	)
	SELECT	ID_CHAMADO
	,		MESA
	FROM	INCIDENTE_ACOES
	WHERE	ID_ACAO IN (SELECT MAX_ID_ACAO FROM ULTIMAS_ATRIBUICOES)
	ORDER	BY ID_CHAMADO;
	
-- DROP VIEW VW_PESOS
CREATE VIEW VW_PESOS AS
	SELECT	A.ID_CHAMADO
	,		COALESCE(D.PESO_DEFAULT, 0) AS PESO
	FROM	(	
				SELECT	ID_CHAMADO
				,		MAX(ID_ACAO) as MAX_ID_ACAO
				FROM	INCIDENTE_ACOES ia 
				WHERE	ULTIMA_ACAO_NOME = 'Atribuição interna'
				AND		MESA NOT IN ( 'A DEFINIR', 'Atendimento de RH', 'Mesa Padrão', 'SVD Manager Template', 'Usuários Finais' )
				GROUP	BY ID_CHAMADO
			) AS A
			--
			INNER JOIN INCIDENTES AS B
			ON	A.ID_CHAMADO = B.ID_CHAMADO
			AND	B.CATEGORIA_MAIOR NOT IN ('Tarefa', 'Demandas Internas')
			--
			INNER JOIN INCIDENTE_ACOES AS C
			ON	A.ID_CHAMADO = C.ID_CHAMADO
			AND	A.MAX_ID_ACAO = C.ID_ACAO
			--
			LEFT OUTER JOIN MESAS_N4_SAP AS D
			ON C.MESA = D.MESA
			--
	ORDER	BY A.ID_CHAMADO;

-- DROP VIEW VW_CATEGORIAS
CREATE VIEW VW_CATEGORIAS AS
	SELECT	DISTINCT ID_CHAMADO
	,		CASE	WHEN CATEGORIA_MAIOR = 'Solicitações de Serviço'
					THEN 'REALIZAR'
					WHEN CATEGORIA_MAIOR = 'Incidentes' AND CATEGORIA LIKE '%CORRIGIR%'
					THEN 'CORRIGIR'
					WHEN CATEGORIA_MAIOR = 'Incidentes'
					THEN 'ORIENTAR'
	 		END AS CATEGORIA
	FROM	INCIDENTES AS A 
	WHERE	CATEGORIA_MAIOR NOT IN ('Tarefa', 'Demandas Internas')
	ORDER	BY A.ID_CHAMADO;

-- DROP VIEW VW_PRAZOS
CREATE VIEW VW_PRAZOS AS 
	SELECT	A.ID_CHAMADO
	,		B.CATEGORIA
	,		A.PESO
	,		CASE	WHEN A.PESO IN (1, 30) AND B.CATEGORIA = 'ORIENTAR' THEN 27 * 60
					WHEN A.PESO IN (1, 30) AND B.CATEGORIA = 'CORRIGIR' THEN 135 * 60
					WHEN A.PESO = 35 THEN 9 * 60
					WHEN B.CATEGORIA = 'REALIZAR' THEN C.PRAZO_OFERTA_M
					ELSE -999999999
			END AS PRAZO
	,		C.OFERTA_CATALOGO 
	FROM	VW_PESOS AS A
			--
			INNER JOIN VW_CATEGORIAS AS B
			ON A.ID_CHAMADO = B.ID_CHAMADO 
			--
			INNER JOIN INCIDENTES AS C
			ON A.ID_CHAMADO = C.ID_CHAMADO 
			--
	WHERE	CATEGORIA_MAIOR NOT IN ('Tarefa', 'Demandas Internas')
	AND		A.PESO > 0
	ORDER 	BY A.ID_CHAMADO;
	
-- DROP VIEW VW_DURACOES
CREATE VIEW VW_DURACOES AS 
	WITH DURACOES AS (
		SELECT	A.ID_CHAMADO
		,		A.CHAMADO_PAI
		,		A.CATEGORIA_MAIOR 
		,		SUM(CASE 	WHEN B.MESA = 'N4-SAP-SUSTENTACAO-PRIORIDADE'
							THEN (CASE WHEN C.MESA = 'N4-SAP-SUSTENTACAO-PRIORIDADE' THEN C.TEMPO_UTIL_ATRIBUICAO_MESA_M ELSE 0 END)
							WHEN B.MESA IN (SELECT MESA FROM MESAS_N4_SAP) 
							THEN C.TEMPO_UTIL_ATRIBUICAO_MESA_M ELSE 0 
				END) AS DURACAO
		FROM	INCIDENTES AS A
				--
				INNER JOIN VW_ULTIMAS_MESAS AS B
				ON 	A.ID_CHAMADO = B.ID_CHAMADO 
				AND B.MESA IN  (SELECT MESA FROM MESAS_N4_SAP)
				--
				INNER JOIN INCIDENTE_ACOES AS C
				ON	B.ID_CHAMADO = C.ID_CHAMADO
				AND B.MESA = C.MESA
				--
		WHERE	A.DATA_RESOLUCAO_CHAMADO IS NOT NULL
		AND		C.ULTIMA_ACAO_NOME = 'Atribuição interna'
		AND		C.TEMPO_UTIL_ATRIBUICAO_MESA_M IS NOT NULL
		GROUP	BY A.ID_CHAMADO
		,		A.CHAMADO_PAI
		,		A.CATEGORIA_MAIOR 
	),
	DURACOES_TAREFAS AS (
		SELECT 	CHAMADO_PAI AS ID_CHAMADO
		,		SUM(DURACAO) AS DURACAO
		FROM 	DURACOES 
		WHERE 	CHAMADO_PAI IS NOT NULL
		AND		ID_CHAMADO LIKE 'T%'
		GROUP	BY CHAMADO_PAI
	)
	SELECT	A.ID_CHAMADO
	,		SUM(A.DURACAO + COALESCE( (SELECT DURACAO FROM DURACOES_TAREFAS WHERE CHAMADO_PAI = A.ID_CHAMADO), 0)) AS DURACAO
	FROM	DURACOES AS A
	WHERE	A.CATEGORIA_MAIOR <> 'Tarefa'
	GROUP	BY A.ID_CHAMADO;

-- DROP VIEW VW_DADOS_MEDICAO 
CREATE VIEW VW_DADOS_MEDICAO AS 
	WITH DADOS AS (
		SELECT	A.ID_CHAMADO
		,		B.CATEGORIA 
		,		C.MESA
		,		D.PESO
		,		E.PRAZO
		,		F.DURACAO
		FROM	INCIDENTES AS A
				--
				LEFT OUTER JOIN VW_CATEGORIAS AS B NOT INDEXED
				ON	A.ID_CHAMADO = B.ID_CHAMADO
				--
				LEFT OUTER JOIN VW_ULTIMAS_MESAS AS C NOT INDEXED
				ON 	A.ID_CHAMADO = C.ID_CHAMADO
				--
				LEFT OUTER JOIN VW_PESOS AS D NOT INDEXED
				ON	A.ID_CHAMADO = D.ID_CHAMADO
				--
				LEFT OUTER JOIN VW_PRAZOS AS E NOT INDEXED
				ON	A.ID_CHAMADO = E.ID_CHAMADO
				--
				LEFT OUTER JOIN VW_DURACOES AS F NOT INDEXED
				ON	A.ID_CHAMADO = F.ID_CHAMADO
				--
		WHERE	A.ID_CHAMADO NOT LIKE 'T%'
		AND		A.ID_CHAMADO NOT IN (SELECT ID_CHAMADO FROM INCIDENTES_OVERRIDE WHERE ESTORNO = 'S')
		AND		A.DATA_RESOLUCAO_CHAMADO IS NOT NULL
		ORDER	BY A.ID_CHAMADO
	)
	SELECT	A.ID_CHAMADO
	,		COALESCE(B.CATEGORIA, A.CATEGORIA) AS CATEGORIA
	,		COALESCE(B.MESA, A.MESA) AS MESA
	,		COALESCE(B.PESO, A.PESO) AS PESO
	,		COALESCE(B.SLA, A.PRAZO) AS PRAZO
	,		COALESCE(B.DURACAO, A.DURACAO) AS DURACAO
	,		B.OBSERVACAO AS OBS_OVERRIDE
	FROM	DADOS AS A
			--
			LEFT OUTER JOIN INCIDENTES_OVERRIDE AS B
			ON 	A.ID_CHAMADO = B.ID_CHAMADO
			--
	ORDER	BY A.ID_CHAMADO;
	
-- DROP VIEW VW_DADOS_MEDICAO_FALTANDO
CREATE VIEW VW_DADOS_MEDICAO_FALTANDO AS 
	SELECT	*
	FROM	VW_DADOS_MEDICAO AS A
	WHERE	A.OBS_OVERRIDE IS NULL
	AND		A.MESA IS NULL OR MESA IN (SELECT MESA FROM MESAS_N4_SAP)
	AND		(CATEGORIA IS NULL OR MESA IS NULL OR PESO IS NULL OR PRAZO IS NULL OR DURACAO IS NULL)
	ORDER	BY ID_CHAMADO;

-- DROP VIEW VW_KPI_PRP
CREATE VIEW VW_KPI_PRP AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END)/ COUNT(*) * 100.0 AS PRP 
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO = 35;

-- DROP VIEW VW_KPI_PRO
CREATE VIEW VW_KPI_PRO AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRO
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'ORIENTAR';
	
-- DROP VIEW VW_KPI_PRC
CREATE VIEW VW_KPI_PRC AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRC
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'CORRIGIR';

-- DROP VIEW VW_KPI_PRS
CREATE VIEW VW_KPI_PRS AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRS 
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'REALIZAR';
	
-- DROP VIEW VW_KPI_PRS_SIMPLES
CREATE VIEW VW_KPI_PRS_SIMPLES AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRS_SIMPLES 
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'REALIZAR'
	AND		PRAZO = 45 * 60;

-- DROP VIEW VW_KPI_PRS_MEDIO
CREATE VIEW VW_KPI_PRS_MEDIO AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRS_MEDIO 
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'REALIZAR'
	AND		PRAZO = 90 * 60;
	
-- DROP VIEW VW_KPI_PRS_COMPLEXO
CREATE VIEW VW_KPI_PRS_COMPLEXO AS
	SELECT	SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) AS VIOLACOES
	,		COUNT(*) AS INCIDENTES
	,		SUM(CASE WHEN DURACAO > PRAZO THEN 1.0 ELSE 0.0 END) / COUNT(*) * 100.0 AS PRS_COMPLEXO 
	FROM	VW_DADOS_MEDICAO
	WHERE	PESO IN (1, 30)
	AND		CATEGORIA = 'REALIZAR'
	AND		PRAZO = 180 * 60;

-- DROP VIEW VW_KPI_CRI
CREATE VIEW VW_KPI_CRI AS
	SELECT	SUM(CASE WHEN COALESCE(C.MESA, B.MESA) IN (SELECT MESA FROM MESAS_N4_SAP) AND A.DATA_RESOLUCAO_CHAMADO IS NOT NULL THEN 1 ELSE 0 END) AS QTD_TRATADOS
	,		SUM(CASE WHEN COALESCE(C.MESA, B.MESA) NOT IN (SELECT MESA FROM MESAS_N4_SAP) THEN 1 ELSE 0 END) AS QTD_ENCAMINHADOS -- PODE ESTAR EM ABERTO
	,		COUNT(*) AS QTD_RECEBIDOS
	,		(
				SUM(CASE WHEN COALESCE(C.MESA, B.MESA) IN (SELECT MESA FROM MESAS_N4_SAP) AND A.DATA_RESOLUCAO_CHAMADO IS NOT NULL THEN 1.0 ELSE 0.0 END)
			+ 	SUM(CASE WHEN COALESCE(C.MESA, B.MESA) NOT IN (SELECT MESA FROM MESAS_N4_SAP) THEN 1.0 ELSE 0.0 END)
			)
			/ COUNT(*) * 100.0 AS CRI 
	FROM	INCIDENTES AS A
			--
			INNER JOIN VW_ULTIMAS_MESAS AS B
			ON 	A.ID_CHAMADO = B.ID_CHAMADO
			--
			LEFT OUTER JOIN INCIDENTES_OVERRIDE AS C
			ON 	A.ID_CHAMADO = C.ID_CHAMADO
			--	
	WHERE	A.ID_CHAMADO NOT IN (SELECT ID_CHAMADO FROM INCIDENTES_OVERRIDE WHERE ESTORNO = 'S');