WITH MESAS AS (
	SELECT	A.ID_CHAMADO
	,		A.ID_ACAO AS ID_ACAO
	,		A.MESA
	,		LEAD(A.ID_ACAO, 1, 999999999) OVER (
				PARTITION BY A.ID_CHAMADO
				ORDER BY A.ID_ACAO
			) AS ID_ACAO_NEXT
	FROM	REL_MEDICAO AS A
	WHERE	A.MESA IS NOT NULL
	ORDER	BY A.ID_CHAMADO
	,		A.ID_ACAO	
),
MESAS_ATUAIS AS (
	SELECT	A.ID_CHAMADO
	,		A.ID_ACAO
	,		COALESCE(A.MESA, B.MESA) AS MESA_ATUAL
	FROM	REL_MEDICAO AS A
			--
			LEFT OUTER JOIN MESAS AS B
			ON 	A.ID_CHAMADO = B.ID_CHAMADO
			AND	A.ID_ACAO > B.ID_ACAO
			AND	A.ID_ACAO < B.ID_ACAO_NEXT
			--
	ORDER	BY A.ID_CHAMADO
	,		A.ID_ACAO
)
UPDATE 	REL_MEDICAO AS UPD
SET		MESA_ATUAL = (
			SELECT 	A.MESA_ATUAL 
			FROM 	MESAS_ATUAIS AS A
			WHERE 	A.ID_CHAMADO	= UPD.ID_CHAMADO 
			AND		A.ID_ACAO		= UPD.ID_ACAO
		);