SELECT	ID_CHAMADO
,		DATA_ABERTURA_CHAMADO
,		DATA_RESOLUCAO_CHAMADO 
,		ID_ACAO 
,		ULTIMA_ACAO_NOME
,		DATA_INICIO_ACAO
,		LEAD(DATA_INICIO_ACAO, 1, DATA_INICIO_ACAO) OVER (
			PARTITION BY ID_CHAMADO
			ORDER BY ID_ACAO
		) AS DATA_PROXIMA_ACAO
,		PENDENCIA
,		MESA_ATUAL
,		DURACAO_M
FROM 	REL_MEDICAO
ORDER	BY ID_CHAMADO 
,		ID_ACAO