-- THIS IS AN UGLY HACK, BUT I NEED BOTH THE TABLES MESAS AND PARAMETERS FILLED

-- PURGE INCIDENTS THAT WEREN'T ACTIONED WITHIN THE MESAS PRIOR THE START OF KPI CALCULATION PERIOD
		
-- PURGE INCIDENTES
DELETE 	FROM INCIDENTES AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);

		
-- PURGE INCIDENTE_ACOES
DELETE 	FROM INCIDENTE_ACOES AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);
		
-- PURGE INCIDENTE_ITENS_B
DELETE 	FROM INCIDENTE_ITENS_B AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);
		

-- PURGE INCIDENTE_ITENS_CAUSA
DELETE 	FROM INCIDENTE_ITENS_CAUSA AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);
		
-- PURGE INCIDENTE_ITENS_SERVICO
DELETE 	FROM INCIDENTE_ITENS_SERVICO AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);

-- PURGE INCIDENTE_SOLICITANTES
DELETE 	FROM INCIDENTE_SOLICITANTES AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);
		
-- PURGE REL_MEDICAO
DELETE 	FROM REL_MEDICAO AS A
WHERE 	A.ID_CHAMADO IN (
			SELECT	ID_CHAMADO
			FROM	REL_MEDICAO AS A
			WHERE	A.MESA_ATUAL IN (SELECT MESA FROM MESAS)
			AND		A.DATA_FIM_ACAO IS NOT NULL
			GROUP	BY ID_CHAMADO
			HAVING 	MAX(DATA_FIM_ACAO) < (SELECT VALOR FROM PARAMS WHERE PARAM = 'HORA_INICIO_APURACAO')
		);
