SELECT	C.MESA_ATUAL AS MESA
,		A.USUARIO_AFETADO 
,		A.NOME_DO_USUARIO_AFETADO
,		COUNT(*) AS QTD
,		SUM(CASE WHEN AVALIACAO < 4 THEN 1 ELSE 0 END) AS RUINS
,		SUM(CASE WHEN AVALIACAO >= 4  THEN 1 ELSE 0 END) AS BONS
FROM	INCIDENTE_SOLICITANTES AS A
		--
		INNER JOIN INCIDENTES AS B
		ON 	A.ID_CHAMADO = B.ID_CHAMADO
		AND B.STATUS_DE_EVENTO <> 'ABERTO'
		--
		INNER JOIN INCIDENTE_ACOES AS C
		ON	B.ID_CHAMADO = C.ID_CHAMADO
		AND	ULTIMA_ACAO = 'y'
		AND	ULTIMA_ACAO_NOME IN ('Encerrar', 'Cancelado', 'Cancelar', 'Resolver')
		AND	C.MESA_ATUAL IN (SELECT MESA FROM MESAS)
		--
		LEFT OUTER JOIN PESQUISAS AS D
		ON	C.ID_CHAMADO = D.ID_CHAMADO
		--
GROUP	BY 1, 2, 3
HAVING 	COUNT(*) >= 20
ORDER	BY 4 DESC