SELECT	A.ID_CHAMADO
,		A.STATUS
,		A.CATEGORIA
,		A.MESA
,		A.PESO
,		A.PRAZO
,		A.DURACAO
,		'N' AS ESTORNO
,		COALESCE(a.OBS_OVERRIDE, 'Registro gerado automaticamente pela view VW_DADOS_MEDICAO_FALTANDO') as OBS_OVERRIDE
FROM	VW_DADOS_MEDICAO_FALTANDO AS A
ORDER	BY A.ID_CHAMADO;

