SELECT	A.ID_CHAMADO 
,		A.STATUS
,		A.CATEGORIA
,		A.MESA
,		C.DATA_ABERTURA_CHAMADO
,		D.ULTIMA_ACAO_NOME
,		D.DATA_INICIO_ACAO AS DATA_ACAO
,		CAST(JULIANDAY('NOW') - JULIANDAY(C.DATA_ABERTURA_CHAMADO) AS INTEGER) AS DIAS_ABERTOS
,		CAST(JULIANDAY('NOW') - JULIANDAY(D.DATA_INICIO_ACAO) AS INTEGER) AS DIAS_DESDE_ULTIMA_ACAO
FROM	VW_DADOS_MEDICAO AS A
		--
		INNER JOIN MESAS_N4_SAP AS B
		ON A.MESA = B.MESA
		--
		INNER JOIN INCIDENTES AS C
		ON	A.ID_CHAMADO = C.ID_CHAMADO
		--
		LEFT OUTER JOIN INCIDENTE_ACOES AS D
		ON 	A.ID_CHAMADO = D.ID_CHAMADO
		AND	D.ID_ACAO = (SELECT MAX(ID_ACAO) FROM INCIDENTE_ACOES WHERE ID_CHAMADO = D.ID_CHAMADO)
		--
WHERE	A.STATUS = 'EM ABERTO'		
AND		CAST(JULIANDAY('NOW') - JULIANDAY(C.DATA_ABERTURA_CHAMADO) AS INTEGER) >= 8
ORDER	BY D.DATA_INICIO_ACAO, C.DATA_ABERTURA_CHAMADO;