SELECT	A.ID_CHAMADO
,		A.CHAMADO_PAI
,		A.CATEGORIA
,		A.OFERTA_CATALOGO
,		A.PRAZO_OFERTA_M 
,		B.ID_ACAO
,		B.ULTIMA_ACAO_NOME AS ACAO_NOME
,		B.PENDENCIA
,		B.MESA_ATUAL
,		B.DATA_INICIO_ACAO AS DATA_ACAO
,		B.DATA_FIM_ACAO AS DATA_FIM_ACAO
,		B.DURACAO_M
FROM	INCIDENTES AS A
		--
		INNER JOIN INCIDENTE_ACOES AS B
		ON 	A.ID_CHAMADO = B.ID_CHAMADO
		--
--WHERE	A.ID_CHAMADO = ?
ORDER	BY A.ID_CHAMADO
,		B.ID_ACAO 
