WITH DADOS AS (
	SELECT	MESA_ATUAL
	,		ULTIMA_ACAO_NOME AS ACAO
	,		PENDENCIA
	,		DURACAO_M
	,		(NTILE(20) OVER (
				PARTITION 	BY MESA_ATUAL, ULTIMA_ACAO_NOME, PENDENCIA 
				ORDER 		BY DURACAO_M
			)-1) * 5 AS PERC
	FROM	INCIDENTE_ACOES
	WHERE	MESA_ATUAL IN (SELECT MESA FROM  MESAS_N4_SAP)
	ORDER	BY MESA_ATUAL
	,		ULTIMA_ACAO_NOME
	,		PENDENCIA
	,		DURACAO_M
),
PERCS AS (
	SELECT	MESA_ATUAL AS MESA
	,		ACAO
	,		PENDENCIA
	,		COUNT(*) AS QTD
	,		SUM(DURACAO_M) AS TEMPO_TOTAL_M
	,		MIN(CASE WHEN PERC =  0 THEN DURACAO_M ELSE NULL END) AS P00
	,		MIN(CASE WHEN PERC =  5 THEN DURACAO_M ELSE NULL END) AS P05
	,		MIN(CASE WHEN PERC = 10 THEN DURACAO_M ELSE NULL END) AS P10
	,		MIN(CASE WHEN PERC = 15 THEN DURACAO_M ELSE NULL END) AS P15
	,		MIN(CASE WHEN PERC = 20 THEN DURACAO_M ELSE NULL END) AS P20
	,		MIN(CASE WHEN PERC = 25 THEN DURACAO_M ELSE NULL END) AS P25
	,		MIN(CASE WHEN PERC = 30 THEN DURACAO_M ELSE NULL END) AS P30
	,		MIN(CASE WHEN PERC = 35 THEN DURACAO_M ELSE NULL END) AS P35
	,		MIN(CASE WHEN PERC = 40 THEN DURACAO_M ELSE NULL END) AS P40
	,		MIN(CASE WHEN PERC = 45 THEN DURACAO_M ELSE NULL END) AS P45
	,		MIN(CASE WHEN PERC = 50 THEN DURACAO_M ELSE NULL END) AS P50
	,		MIN(CASE WHEN PERC = 55 THEN DURACAO_M ELSE NULL END) AS P55
	,		MIN(CASE WHEN PERC = 60 THEN DURACAO_M ELSE NULL END) AS P60
	,		MIN(CASE WHEN PERC = 65 THEN DURACAO_M ELSE NULL END) AS P65
	,		MIN(CASE WHEN PERC = 70 THEN DURACAO_M ELSE NULL END) AS P70
	,		MIN(CASE WHEN PERC = 75 THEN DURACAO_M ELSE NULL END) AS P75
	,		MIN(CASE WHEN PERC = 80 THEN DURACAO_M ELSE NULL END) AS P80
	,		MIN(CASE WHEN PERC = 85 THEN DURACAO_M ELSE NULL END) AS P85
	,		MIN(CASE WHEN PERC = 90 THEN DURACAO_M ELSE NULL END) AS P90
	,		MIN(CASE WHEN PERC = 95 THEN DURACAO_M ELSE NULL END) AS P95
	FROM	DADOS
	GROUP	BY MESA_ATUAL
	,		ACAO
	,		PENDENCIA
	HAVING	COUNT(*) > 20
	AND		SUM(DURACAO_M) > 1
)
SELECT	*
FROM	PERCS
ORDER	BY TEMPO_TOTAL_M DESC