WITH ULTIMAS_MESAS AS (
	SELECT	ID_CHAMADO
	,		MESA_ATUAL AS ULTIMA_MESA
	FROM	INCIDENTE_ACOES
	WHERE	ULTIMA_ACAO = 'y' -- CUIDADO COM CAIXA ALTA!!!
)
SELECT	B.ID_CHAMADO
,		CASE	WHEN B.ID_CHAMADO LIKE 'T%' THEN 'REALIZAR'
				WHEN B.CATEGORIA LIKE '%CORRIGIR%' THEN 'CORRIGIR'
				ELSE 'ORIENTAR'
		END AS CATEGORIA
,		C.ULTIMA_MESA
--,		COUNT(*) AS QTD_ACOES
,		SUM(CASE WHEN PENDENCIA = 'N' THEN DURACAO_M ELSE 0 END) AS DURACAO_M
,		SUM(CASE WHEN PENDENCIA = 'S' THEN DURACAO_M ELSE 0 END) AS PENDENCIA_M
,		SUM(DURACAO_M) AS TEMPO_M
FROM	INCIDENTE_ACOES AS A
		--
		INNER JOIN INCIDENTES AS B
		ON 	A.ID_CHAMADO = B.ID_CHAMADO
		--
		LEFT OUTER JOIN ULTIMAS_MESAS AS C
		ON	A.ID_CHAMADO = C.ID_CHAMADO
		--
WHERE	A.MESA_ATUAL = 'N4-SAP-SUSTENTACAO-ESCALADOS'
AND		A.ID_CHAMADO IN (
			SELECT 	ID_CHAMADO 
			FROM 	INCIDENTE_ACOES
			WHERE	MESA_ATUAL = 'N4-SAP-SUSTENTACAO-ESCALADOS'
		)
GROUP	BY 1, 2, 3
ORDER	BY 2, 1