WITH INCS AS (
	SELECT	DISTINCT ULTIMA_MESA AS MESA
	,		TIPO
	,		PESO
	,		ID_CHAMADO
	,		CHAMADO_PAI
	,		PRAZO
	,		SOMA_DURACOES_CHAMADO
	FROM	REL_MEDICAO_STG AS R
	WHERE	TIPO IN ('ORIENTAR', 'CORRIGIR', 'EXECUTAR')
	
)
, TASKS AS (
	SELECT	CHAMADO_PAI
	,		SUM(SOMA_DURACOES_CHAMADO) AS SOMA_DURACOES_CHAMADO
	FROM (
		SELECT	DISTINCT CHAMADO_PAI, SOMA_DURACOES_CHAMADO
		FROM	REL_MEDICAO_STG
		WHERE	TIPO = 'EXECUTAR - TAREFA'
		AND		CHAMADO_PAI IS NOT NULL
		AND		PESO > 0
		ORDER	BY 1, 2
	) AS T
	GROUP	BY CHAMADO_PAI
)
SELECT	MESA
,		TIPO
,		PESO
,		ID_CHAMADO
,		PRAZO
,		COALESCE((SELECT SUM(SOMA_DURACOES_CHAMADO) FROM TASKS WHERE CHAMADO_PAI = I.ID_CHAMADO), SOMA_DURACOES_CHAMADO) AS SOMA_DURACOES_CHAMADO
,		CASE 	WHEN PESO = 0
				THEN 'N/A'
				WHEN COALESCE((SELECT SUM(SOMA_DURACOES_CHAMADO) FROM TASKS WHERE CHAMADO_PAI = I.ID_CHAMADO), SOMA_DURACOES_CHAMADO) >= PRAZO
				THEN 'S'
				ELSE 'N'
		END AS VIOLACAO_SLA
FROM	INCS AS I
ORDER	BY 1, 2, 3, 4