SELECT	CASE 	WHEN COUNT(*) = 1 THEN 'OK'
				ELSE 'FALHA IMPORTAÇÃO' 
		END AS CHECK_IMPORTACAO
FROM	(		
			SELECT	COUNT(*) FROM VW_REL_MEDICAO
			UNION	
			SELECT	COUNT(*) FROM REL_MEDICAO
		) AS COUNTS
