SELECT	TABLENAME = T.NAME
,		INDEXNAME = IND.NAME
--,		INDEXID = IND.INDEX_ID,
--,		COLUMNID = IC.INDEX_COLUMN_ID,
,		COLUMNNAME = COL.NAME
,		IND.*
,		IC.*
,		COL.* 
FROM 	SYS.INDEXES IND 
		--
		INNER JOIN SYS.INDEX_COLUMNS IC 
		ON  IND.OBJECT_ID = IC.OBJECT_ID 
		AND IND.INDEX_ID = IC.INDEX_ID
		--
		INNER JOIN SYS.COLUMNS COL 
		ON 	IC.OBJECT_ID = COL.OBJECT_ID 
		AND IC.COLUMN_ID = COL.COLUMN_ID 
		--
		INNER JOIN SYS.TABLES T 
		ON 	IND.OBJECT_ID = T.OBJECT_ID 
		--
WHERE	T.NAME 						LIKE 'act_reg'
AND		IND.IS_PRIMARY_KEY 			= 0 
AND		IND.IS_UNIQUE 				= 0 
AND		IND.IS_UNIQUE_CONSTRAINT 	= 0 
AND		T.IS_MS_SHIPPED 			= 0 
ORDER 	BY T.NAME
,		IND.NAME
,		IND.INDEX_ID
,		IC.INDEX_COLUMN_ID;