WITH ULTIMAS_ATRIBUICOES AS (
	SELECT	MAX(ID_ACAO) as MAX_ID_ACAO
	FROM	INCIDENTE_ACOES ia 
	WHERE	ULTIMA_ACAO_NOME = 'Atribuição interna'
	--AND		ID_CHAMADO IN (SELECT ID_CHAMADO FROM INCIDENTES WHERE STATUS_DE_EVENTO = 'Aberto')
	AND		MESA NOT IN (
			    'A DEFINIR',
			    'Atendimento de RH',
			    'Mesa Padrão',
			    'SVD Manager Template',
			    'Usuários Finais',
			    'N4-SAP-SUSTENTACAO-PRIORIDADE',
			    'N4-SAP-SUSTENTACAO-ESCALADOS'
		    )
	GROUP	BY ID_CHAMADO
)
SELECT	ID_CHAMADO
,		MESA
FROM	INCIDENTE_ACOES
WHERE	ID_ACAO IN (SELECT MAX_ID_ACAO FROM ULTIMAS_ATRIBUICOES)
ORDER	BY ID_CHAMADO