INSERT INTO INCIDENTES_OVERRIDE(
	ID_CHAMADO
,   STATUS
,   CATEGORIA
,   MESA
,   PESO
,   PRAZO
,   DURACAO
,   ESTORNO
,   OBSERVACAO
) VALUES(
	? -- ID_CHAMADO
,   ? -- STATUS
,   ? -- CATEGORIA
,   ? -- MESA
,   ? -- PESO
,   ? -- PRAZO
,   ? -- DURACAO
,   ? -- ESTORNO
,   ? -- OBSERVACAO
)
ON CONFLICT(ID_CHAMADO) DO 
UPDATE  SET 
		STATUS      = EXCLUDED.STATUS
,       CATEGORIA   = EXCLUDED.CATEGORIA
,       MESA        = EXCLUDED.MESA
,       PESO        = EXCLUDED.PESO
,       PRAZO       = EXCLUDED.PRAZO
,       DURACAO     = EXCLUDED.DURACAO
,       ESTORNO     = EXCLUDED.ESTORNO
,       OBSERVACAO  = EXCLUDED.OBSERVACAO
